<#
.SYNOPSIS
    Installs (or removes) AKForeverTooltip_SavedState, a companion addon that works around
    the WoW: Forever beta client writing SavedVariables on logout but never reading them back.

.DESCRIPTION
    A SavedVariables file is plain Lua ("AKForeverTooltipDB = { ... }"). The client will not
    load it as saved data, but runs it happily as addon code. This creates

        Interface\AddOns\AKForeverTooltip_SavedState\
            AKForeverTooltip_SavedState.toc
            Before.lua
            SV\            <- directory junction to WTF\Account\<account>\SavedVariables
            After.lua

    whose .toc lists SV\AKForeverTooltip.lua. The main addon declares it as an OptionalDep,
    so it runs first. Same mechanism as WeaponBuffs' bridge, verified in the 1.60.1 beta.

    Not needed once Blizzard fixes the client: run with -Remove.

.EXAMPLE
    .\tools\Install-SavedStateBridge.ps1
    .\tools\Install-SavedStateBridge.ps1 -Remove
#>
[CmdletBinding()]
param(
    [string]$ClientPath = 'C:\Program Files (x86)\World of Warcraft\_classic_beta_',
    [string]$AddonName = 'AKForeverTooltip',
    [string]$GlobalName = 'AKForeverTooltipDB',

    # Folder name under WTF\Account. Default: the most recently used account.
    [string]$Account,

    [switch]$Remove
)

$ErrorActionPreference = 'Stop'

$bridgeName = "${AddonName}_SavedState"
$addonDir = Join-Path $ClientPath "Interface\AddOns\$bridgeName"
$svLink = Join-Path $addonDir 'SV'

function Remove-JunctionOnly([string]$Path) {
    # WARNING: in Windows PowerShell 5.1, "Remove-Item -Recurse" on a junction deletes the
    # CONTENTS OF THE TARGET - here, every addon's saved settings. rmdir without /s removes
    # only the link itself.
    if (-not (Test-Path -LiteralPath $Path)) { return }
    $item = Get-Item -LiteralPath $Path -Force
    if ($item.LinkType -ne 'Junction') {
        throw "$Path exists but is not a junction - refusing to touch it."
    }
    cmd /c rmdir "`"$Path`"" | Out-Null
    if (Test-Path -LiteralPath $Path) { throw "could not remove junction $Path" }
}

function Remove-Bridge {
    Remove-JunctionOnly $svLink
    if (Test-Path -LiteralPath $addonDir) {
        $reparse = Get-ChildItem -LiteralPath $addonDir -Force -Recurse |
            Where-Object { $_.Attributes -band [IO.FileAttributes]::ReparsePoint }
        if ($reparse) { throw "unexpected links left in ${addonDir}: $($reparse.FullName -join ', ')" }
        Remove-Item -LiteralPath $addonDir -Recurse -Force
    }
}

if ($Remove) {
    Remove-Bridge
    Write-Host "Removed $addonDir"
    return
}

$accountRoot = Join-Path $ClientPath 'WTF\Account'
if (-not (Test-Path -LiteralPath $accountRoot)) { throw "no WTF\Account under $ClientPath - log in once first." }

if (-not $Account) {
    $candidates = Get-ChildItem -LiteralPath $accountRoot -Directory |
        Where-Object { Test-Path -LiteralPath (Join-Path $_.FullName 'SavedVariables') } |
        Sort-Object { (Get-Item -LiteralPath (Join-Path $_.FullName 'SavedVariables')).LastWriteTime } -Descending
    if (-not $candidates) { throw "no account with a SavedVariables folder under $accountRoot" }
    $Account = @($candidates)[0].Name
}
$svDir = Join-Path (Join-Path $accountRoot $Account) 'SavedVariables'
if (-not (Test-Path -LiteralPath $svDir)) { throw "not found: $svDir" }

# The .toc names SV\<addon>.lua; make sure it exists so a fresh install does not log
# "couldn't open". The client overwrites it on the next logout.
$svFile = Join-Path $svDir "$AddonName.lua"
if (-not (Test-Path -LiteralPath $svFile)) { Set-Content -LiteralPath $svFile -Value '' -Encoding ascii }

Remove-Bridge
New-Item -ItemType Directory -Path $addonDir | Out-Null

Set-Content -LiteralPath (Join-Path $addonDir "$bridgeName.toc") -Encoding ascii -Value @(
    '## Interface: 16001'
    "## Title: $AddonName |cff888888(saved state bridge)|r"
    "## Notes: Beta workaround: the WoW: Forever client never reads SavedVariables back, so this loads $AddonName's saved file as code. Remove it once Blizzard fixes that."
    '## Author: Purrdee'
    '## Version: 1'
    ''
    'Before.lua'
    "SV\$AddonName.lua"
    'After.lua'
)
Set-Content -LiteralPath (Join-Path $addonDir 'Before.lua') -Encoding ascii -Value @(
    "-- Generated by $AddonName\tools\Install-SavedStateBridge.ps1."
    "${bridgeName}Bridge = { version = 1 }"
)
Set-Content -LiteralPath (Join-Path $addonDir 'After.lua') -Encoding ascii -Value @(
    '-- Lets the addon tell "loaded by this bridge" from "loaded by the client".'
    "${bridgeName}Bridge.table = $GlobalName"
)

New-Item -ItemType Junction -Path $svLink -Target $svDir | Out-Null

Write-Host "Installed $addonDir"
Write-Host "  account : $Account"
Write-Host "  SV      -> $svDir"
Write-Host 'Restart the game client completely - a new addon folder is not picked up by /reload.'
